version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432
  app:
    command: ["./wait-for-it.sh", "db:5432", "--", "app"]
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - 2112:2112
    depends_on:
      - db
    links:
      - db